# Generated by Django 4.2.dev20220621081037 on 2023-01-22 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSight', '0004_report_info_delete_myothermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userId', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phonenumber', models.CharField(max_length=11)),
                ('address', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='report_info',
        ),
    ]
