# Generated by Django 4.2.dev20220621081037 on 2023-01-22 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSight', '0005_user_details_delete_report_info'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
