# Generated by Django 4.2.dev20220621081037 on 2023-01-22 10:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('SafeSight', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='userId',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
