# Generated by Django 4.2.dev20220621081037 on 2023-01-22 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSight', '0008_alter_user_details_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='phonenumber',
            field=models.IntegerField(),
        ),
    ]
