# Generated by Django 4.2.dev20220621081037 on 2023-01-22 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SafeSight', '0009_alter_user_details_phonenumber'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_details',
        ),
    ]
